### ISSUE TITLE
mkdir EACCESS Error on server

### ISSUE THREAD

**Issue by Becker-Asano** [kumarasinghe/slimauth#1]
Hi, when I try to install an express app that uses your slimauth library on my server, then I get the following error:

> Error: EACCES: permission denied, mkdir '/usr/share/passenger/helper-scripts/slimauth'
    at Object.mkdirSync (fs.js:764:3)
    at Object.<anonymous> (/var/www/vhosts/[..]/node_modules/slimauth/slimauth.js:1:2168)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/var/www/vhosts/[..]/index.js:12:18) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/share/passenger/helper-scripts/slimauth'

It seems as if the directory `slimauth` cannot be created. This directory was present already, when I started the app. I deleted the directory and still get the same error message.
On localhost under Windows 10 I don't have any trouble.

**Comment by Becker-Asano** [comment]
Hi again, I found a solution:
I changed `DATA_DIR=require("path").dirname(require.main.filename)+"/slimauth"` in slimauth.js to `DATA_DIR="/slimauth"` on my server. Now it works..

I think the following warnings when calling `npm install slimauth` might have to do with this:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

On Windows these warnings might not appear.

Hope this helps...

**Comment by kumarasinghe** [comment]
@Becker-Asano Hi. Many thanks for the update. I tested this on Linux, and it works fine. Probably your node doesn't have write permission to `/usr/share/passenger/helper-scripts`  Have you `chmod 775` the directory?.  And those installation warnings aren't caused by slim chat. May be delete your `node_modules` and run `npm install` followed by `npm rebuild`
